"""Pydantic models for Mellea assets and entities."""

from mellea_api.models.artifact import (
    Artifact,
    ArtifactType,
    ArtifactUsage,
)
from mellea_api.models.assets import (
    AssetMetadata,
    CompositionAsset,
    DependencySpec,
    ModelAsset,
    ModelParams,
    PackageRef,
    ProgramAsset,
    ResourceProfile,
    SharedAccess,
    SlotMetadata,
    SlotSignature,
)
from mellea_api.models.audit import (
    AuditAction,
    AuditEvent,
    AuditEventListResponse,
    AuditResourceType,
)
from mellea_api.models.build import (
    BuildContext,
    BuildResult,
    BuildStage,
    LayerCacheEntry,
)
from mellea_api.models.common import (
    AccessType,
    EnvironmentStatus,
    ModelProvider,
    ModelScope,
    Permission,
    RunStatus,
    SharingMode,
)
from mellea_api.models.environment import Environment, ResourceLimits
from mellea_api.models.notification import (
    Notification,
    NotificationCreateRequest,
    NotificationListResponse,
    NotificationPriority,
    NotificationType,
    NotificationUpdateRequest,
    WebSocketMessage,
)
from mellea_api.models.permission import (
    AccessControlEntry,
    PermissionCheck,
    ResourceType,
    permission_includes,
)
from mellea_api.models.user import (
    AuthConfig,
    AuthProvider,
    TokenResponse,
    User,
    UserCreate,
    UserLogin,
    UserPublic,
    UserQuotas,
    UserRole,
    UserStatus,
)

__all__ = [
    "AccessControlEntry",
    "AccessType",
    "Artifact",
    "ArtifactType",
    "ArtifactUsage",
    "AssetMetadata",
    "AuditAction",
    "AuditEvent",
    "AuditEventListResponse",
    "AuditResourceType",
    "Notification",
    "NotificationCreateRequest",
    "NotificationListResponse",
    "NotificationPriority",
    "NotificationType",
    "NotificationUpdateRequest",
    "WebSocketMessage",
    "AuthConfig",
    "AuthProvider",
    "BuildContext",
    "BuildResult",
    "BuildStage",
    "CompositionAsset",
    "DependencySpec",
    "Environment",
    "EnvironmentStatus",
    "LayerCacheEntry",
    "ModelAsset",
    "ModelParams",
    "ModelProvider",
    "ModelScope",
    "PackageRef",
    "Permission",
    "PermissionCheck",
    "permission_includes",
    "ProgramAsset",
    "ResourceLimits",
    "ResourceProfile",
    "ResourceType",
    "RunStatus",
    "SharedAccess",
    "SharingMode",
    "SlotMetadata",
    "SlotSignature",
    "TokenResponse",
    "User",
    "UserCreate",
    "UserLogin",
    "UserPublic",
    "UserQuotas",
    "UserRole",
    "UserStatus",
]
