"""Pydantic models for Mellea assets and entities."""

from mellea_api.models.assets import (
    AssetMetadata,
    CompositionAsset,
    DependencySpec,
    ModelAsset,
    ModelParams,
    PackageRef,
    ProgramAsset,
    ResourceProfile,
    SharedAccess,
    SlotMetadata,
    SlotSignature,
)
from mellea_api.models.common import SharingMode, RunStatus, ModelProvider, ModelScope
from mellea_api.models.user import (
    AuthConfig,
    AuthProvider,
    TokenResponse,
    User,
    UserCreate,
    UserLogin,
    UserPublic,
    UserQuotas,
    UserRole,
    UserStatus,
)

__all__ = [
    "AssetMetadata",
    "AuthConfig",
    "AuthProvider",
    "CompositionAsset",
    "DependencySpec",
    "ModelAsset",
    "ModelParams",
    "ModelProvider",
    "ModelScope",
    "PackageRef",
    "ProgramAsset",
    "ResourceProfile",
    "RunStatus",
    "SharedAccess",
    "SharingMode",
    "SlotMetadata",
    "SlotSignature",
    "TokenResponse",
    "User",
    "UserCreate",
    "UserLogin",
    "UserPublic",
    "UserQuotas",
    "UserRole",
    "UserStatus",
]
